/* Autogenerated by mlir-tblgen; don't manually edit. */

#include "proto/enumgen.pb.h"

#include <clang/CIR/Dialect/IR/CIRDialect.h>

namespace protocir {
class EnumsDeserializer {
public:
// ATT or Intel
  static ::cir::AsmFlavor
  deserializeAsmFlavor(const CIRAsmFlavor &pKind);

// Binary opcode for atomic fetch operations
  static ::cir::AtomicFetchKind
  deserializeAtomicFetchKind(const CIRAtomicFetchKind &pKind);

// await kind
  static ::cir::AwaitKind
  deserializeAwaitKind(const CIRAwaitKind &pKind);

// binary operation (arith and logic) kind
  static ::cir::BinOpKind
  deserializeBinOpKind(const CIRBinOpKind &pKind);

// checked binary arithmetic operation kind
  static ::cir::BinOpOverflowKind
  deserializeBinOpOverflowKind(const CIRBinOpOverflowKind &pKind);

// calling convention
  static ::cir::CallingConv
  deserializeCallingConv(const CIRCallingConv &pKind);

// case kind
  static ::cir::CaseOpKind
  deserializeCaseOpKind(const CIRCaseOpKind &pKind);

// cast kind
  static ::cir::CastKind
  deserializeCastKind(const CIRCastKind &pKind);

// Designate limits for begin/end of catch param handling
  static ::cir::CatchParamKind
  deserializeCatchParamKind(const CIRCatchParamKind &pKind);

// compare operation kind
  static ::cir::CmpOpKind
  deserializeCmpOpKind(const CIRCmpOpKind &pKind);

// three-way comparison ordering kind
  static ::cir::CmpOrdering
  deserializeCmpOrdering(const CIRCmpOrdering &pKind);

// complex number binary operation kind
  static ::cir::ComplexBinOpKind
  deserializeComplexBinOpKind(const CIRComplexBinOpKind &pKind);

// complex multiplication and division implementation
  static ::cir::ComplexRangeKind
  deserializeComplexRangeKind(const CIRComplexRangeKind &pKind);

// dynamic cast kind
  static ::cir::DynamicCastKind
  deserializeDynamicCastKind(const CIRDynamicCastKind &pKind);

// Linkage type/kind
  static ::cir::GlobalLinkageKind
  deserializeGlobalLinkageKind(const CIRGlobalLinkageKind &pKind);

// inlineKind
  static ::cir::InlineKind
  deserializeInlineKind(const CIRInlineKind &pKind);

// Memory order according to C++11 memory model
  static ::cir::MemOrder
  deserializeMemOrder(const CIRMemOrder &pKind);

// the behavior for signed overflow
  static ::cir::sob::SignedOverflowBehavior
  deserializeSignedOverflowBehavior(const CIRSignedOverflowBehavior &pKind);

// size info type
  static ::cir::SizeInfoType
  deserializeSizeInfoType(const CIRSizeInfoType &pKind);

// Source language
  static ::cir::SourceLanguage
  deserializeSourceLanguage(const CIRSourceLanguage &pKind);

// TLS model
  static ::cir::TLS_Model
  deserializeTLS_Model(const CIRTLS_Model &pKind);

// unary operation kind
  static ::cir::UnaryOpKind
  deserializeUnaryOpKind(const CIRUnaryOpKind &pKind);

// C/C++ visibility
  static ::cir::VisibilityKind
  deserializeVisibilityKind(const CIRVisibilityKind &pKind);


};
} // namespace protocir
