name: Build and push docker image of ClangIR (MacOS)

on:
  workflow_dispatch:

env:
  CLANGIR_REPOSITORY: "explyt/clangir"
  CLANGIR_VERSION: "21.03.2025-rc"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dummy input
        run: mkdir clangir

      - name: Install Docker
        run: |
          brew install docker --formula

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create image tag
        run: |
          echo "IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/clangir_macos-latest_build:${{ env.CLANGIR_REPOSITORY }}-${{ env.CLANGIR_VERSION }}" \
            >> $GITHUB_ENV

      - name: Copy clangir to Docker image and push
        run: |
          docker build \
            -t ${{ env.IMAGE_TAG }} \
            -f ./docker/DockerfileMacOS \
            .
          docker push ${{ env.IMAGE_TAG }}
