name: Build and push docker image of ClangIR (MacOS)

on:
  workflow_dispatch:

env:
  CLANGIR_REPOSITORY: "explyt/clangir"
  CLANGIR_NORMALIZED_REPO: "explyt_clangir"
  CLANGIR_VERSION: "21.03.2025-rc"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout clangir repo
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CLANGIR_VERSION }}
          repository: ${{ env.CLANGIR_REPOSITORY }}
          path: clangir

      - name: Cache clangir build
        id: cache-clangir-build
        uses: actions/cache@v4
        with:
          path: clangir/llvm/build
          key: macos-latest-${{ env.CLANGIR_NORMALIZED_REPO }}-${{ env.CLANGIR_VERSION }}-clangir-build

      - name: Build clangir
        if: steps.cache-clangir-build.outputs.cache-hit != 'true'
        run: |
          cd clangir/llvm && mkdir -p build && cd build
          cmake -GNinja -DLLVM_ENABLE_PROJECTS="clang;mlir" -DCLANG_ENABLE_CIR=ON -DCMAKE_BUILD_TYPE=MinSizeRel ..
          ninja

  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore clangir built on macOS
        uses: actions/cache/restore@v4
        with:
          key: macos-latest-${{ env.CLANGIR_NORMALIZED_REPO }}-${{ env.CLANGIR_VERSION }}-clangir-build
          path: clangir/llvm/build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create image tag
        run: |
          echo "IMAGE_TAG=clangir_macos-latest_build:${{ env.CLANGIR_NORMALIZED_REPO }}-${{ env.CLANGIR_VERSION }}" \
            >> $GITHUB_ENV

      - name: Build and push Docker image with clangir
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/DockerfileMacOS
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_TAG }}
