name: Build and push docker image of ClangIR (MacOS)

on:
  workflow_dispatch:

env:
  CLANGIR_REPOSITORY: "explyt/clangir"
  CLANGIR_NORMALIZED_REPO: "explyt_clangir"
  CLANGIR_VERSION: "21.03.2025-rc"

jobs:
  build:
    runs-on: macos-latest

    steps:

      - name: Cache clangir build
        id: cache-clangir-build
        uses: actions/cache@v4
        with:
          path: clangir
          key: dummy-input

      - name: Dummy input
        run: |
          mkdir clangir
          cd clangir
          touch something.txt
          echo hello >> something.txt

  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore clangir built on macOS
        uses: actions/cache/restore@v4
        with:
          key: dummy-input
          path: clangir

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create image tag
        run: |
          echo "IMAGE_TAG=clangir_macos-latest_build:${{ env.CLANGIR_NORMALIZED_REPO }}-${{ env.CLANGIR_VERSION }}" \
            >> $GITHUB_ENV

      - name: Build and push Docker image with clangir
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/DockerfileMacOS
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_TAG }}
