name: Build and push docker image of ClangIR (MacOS)

on:
  workflow_dispatch:

env:
  CLANGIR_REPOSITORY: "explyt/clangir"
  CLANGIR_VERSION: "21.03.2025-rc"

jobs:
  env-setup:
    runs-on: macos-latest
    outputs:
      normalized-repo: ${{ steps.set.outputs.normalized-repo }}
    steps:
    - name: Normalize clangir repository name
      id: set
      run: |
          echo "normalized-repo=$(echo ${{ env.CLANGIR_REPOSITORY }} | sed 's:/:_:g')" >> $GITHUB_ENV

  build:
    runs-on: macos-latest
    needs: env-setup

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dummy input
        run: |
          mkdir clangir
          cd clangir
          touch something.txt
          echo hello >> something.txt

      - name: Upload clangir build
        uses: actions/upload-artifact@v4
        with:
          name: clangir-macos-build-${{ needs.env-setup.outputs.normalized-repo }}-${{ env.CLANGIR_VERSION }}
          path: clangir
          retention-days: 1

  upload:
    runs-on: ubuntu-latest
    needs: [env-setup, build]

    steps:
      - name: Download clangir built on macOS
        uses: actions/download-artifact@v4
        with:
          name: clangir-macos-build-${{ needs.env-setup.outputs.normalized-repo }}-${{ env.CLANGIR_VERSION }}
          path: clangir

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create image tag
        run: |
          echo "IMAGE_TAG=clangir_macos-latest_build:${{ needs.env-setup.outputs.normalized-repo }}-${{ env.CLANGIR_VERSION }}" \
            >> $GITHUB_ENV

      - name: Build and push Docker image with clangir
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/DockerfileMacOS
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_TAG }}
