name: Build and push docker image of ClangIR (MacOS)

on:
  workflow_dispatch:

env:
  CLANGIR_REPOSITORY: "explyt/clangir"
  CLANGIR_VERSION: "21.03.2025-rc"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dummy input
        run: mkdir clangir

      - name: Install and start Docker
        run: |
          brew install docker --cask
          brew services start docker-machine

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Copy clangir to Docker image and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/DockerfileMacOS
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/macos-latest-${{ env.CLANGIR_REPOSITORY }}-${{ env.CLANGIR_VERSION }}-clangir-build
