name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1,4'
  workflow_call:

env:
  CLANGIR_REPOSITORY: "explyt/clangir"
  CLANGIR_VERSION: "20.03.2025-rc"

jobs:
    build-clangir:
      uses: ./.github/workflows/build.yml
      with:
        clangir_repository: ${{ github.env.CLANGIR_REPOSITORY }}
        clangir_version: ${{ github.env.CLANGIR_VERSION }}

    run-tests:
      uses: ./.github/workflows/gsac-test.yml
      with:
        clangir_repository: ${{ github.env.CLANGIR_REPOSITORY }}
        clangir_version: ${{ github.env.CLANGIR_VERSION }}
