name: CI

on:
  workflow_dispatch:

jobs:
  get-clangir-id:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read JSON
        id: set-matrix
        run: echo "matrix=$(jq -c . < ./.github/workflows/clangir-version.json)" >> $GITHUB_OUTPUT

  build-clangir:
    needs: get-clangir-id
    uses: ./.github/workflows/build.yml
    secrets: inherit

  run-gsac-tests:
    needs: [get-clangir-id, build-clangir]
    uses: ./.github/workflows/gsac-test.yml
    strategy:
      matrix:
        clangir: ${{ fromJSON(needs.get-clangir-id.outputs.matrix) }}
    with:
      CLANGIR_REPOSITORY: ${{ matrix.clangir.repository }}
      CLANGIR_VERSION: ${{ matrix.clangir.version }}

  run-juliet-tests:
    if: github.event_name == 'workflow_dispatch'
    needs: [get-clangir-id, build-clangir]
    uses: ./.github/workflows/juliet-c-test.yml
    strategy:
      matrix:
        clangir: ${{ fromJSON(needs.get-clangir-id.outputs.matrix) }}
    with:
      CLANGIR_REPOSITORY: ${{ matrix.clangir.repository }}
      CLANGIR_VERSION: ${{ matrix.clangir.version }}
