name: GSAC Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GSAC_REPOSITORY: "explyt/GSAC"
  GSAC_COMMIT: "DanielELog/fix_macos_build"
  GSAC_DIRECTORY: "gsac"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    name: Run GSAC Tests
    runs-on: ${{ matrix.os }}
    needs: build

    steps:
    - name: Checkout GSAC
      uses: actions/checkout@v4
      with:
        ref: ${{ env.GSAC_COMMIT }}
        repository: ${{ env.GSAC_REPOSITORY }}
        path: ${{ env.GSAC_DIRECTORY }}

    - name: Export stdlib for MacOS
      if: startsWith(runner.os, 'macOS')
      run: export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)

    - name: Run GSAC Test Suite
      run: ./.github/workflows/run_gsac_tests.py "." ${{ env.GSAC_DIRECTORY }}

    - name: Upload first failed test to GitHub artifacts
      uses: actions/upload_artifact@v4
      if: failure()
      with:
        name: failed-test-original
        with: test.s

    - name: Upload failed deserialization to GitHub artifacts
      uses: actions/upload_artifact@v4
      if: failure()
      with:
        name: failed-test-deserialized
        with: test.cir

    - name: Upload failed test's diff to GitHub artifacts
      uses: actions/upload_artifact@v4
      if: failure()
      with:
        name: failed-test-diff
        with: test.out
