name: Juliet-C Test Suite

on:
  workflow_call:
    inputs:
      CLANGIR_REPOSITORY:
        description: "Name of ClangIR repository"
        required: true
        type: string
      CLANGIR_VERSION:
        description: "ClangIR version to use"
        required: true
        type: string

jobs:
  gsac-test:
    uses: ./.github/workflows/run-test-suite.yml
    with:
      CLANGIR_REPOSITORY: ${{ inputs.CLANGIR_REPOSITORY }}
      CLANGIR_VERSION: ${{ inputs.CLANGIR_VERSION }}
      TEST_REPOSITORY: "explyt/juliet-c"
      TEST_COMMIT: "juliet-db-flat"
      SEARCH_FOR_CIR: true
